name: Publish

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Verify
        uses: ./.github/actions/verify

      - name: Set up npm authentication
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - name: Publish packages
        run: npm run changeset:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
